package com.sicuro.escrow.exception

class UserAlreadyExistException(override val message: String): RuntimeException(message);
